### PR TITLE
Catch and log if rsync fails

### PR DESCRIPTION
**Pull request by pbitzer**

### CODE REVIEW

**Review by CAM-Gerlach — COMMENTED** [review]
If you want this to target 0.3.x (which has the Sindri 0.3.x website config added), as you probably do (or 0.2.x, as opposed to `master` which is for Sindri 0.4.x with the additional discussed changes I'm working on), this will need to be rebased `--onto` that branch, but I can just do when its ready to merge unless you really want to. I marked it as draft as a reminder.

**Comment by pbitzer** [comment]
Ah, I got my versions mixed up. I thought 0.3.x was what we've been targeting. 

I thought I changed the target to 0.3.x, but feel free to merge to whatever what one you think is appropriate.

**Comment by CAM-Gerlach** [comment]
> Ah, I got my versions mixed up. I thought 0.3.x was what we've been targeting.

Yeah, either 0.3.x or 0.2.x should be fine, since 0.3.x just adds all the Sindri stuff in the `website` directory. The issue is while you had the PR target branch correctly set to `0.3.x`, the `rsync-failure-patch` branch was created off `master` rather than `0.3.x`, i.e. you typed `git switch -c rsync-failure-patch` while on `master` rather than `0.3.x`, which meant the `master` commits (e.g. changing the version) not on 0.3.x were included as part of your feature branch.

Just in case you need it in the future, the way to change your feature branch's base branch is by running

```shell
git rebase --onto new-base old-base your-feature-branch
```

i.e. for this case

```shell
git rebase --onto 0.3.x master rsync-failure-patch
```

Anyway, I'll go ahead to rebase and merge this :+1:

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @pbitzer !

**Pull request merged**
